"""add video processing fields for HLS conversion

Revision ID: 832a0fa50133
Revises: 97f1119abbda
Create Date: 2025-11-05 16:12:31.766627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '832a0fa50133'
down_revision: Union[str, None] = '97f1119abbda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('raw_video_url', sa.String(), nullable=True))
    op.add_column('video', sa.Column('raw_video_key', sa.String(), nullable=True))
    op.add_column('video', sa.Column('processed_video_url', sa.String(), nullable=True))
    op.add_column('video', sa.Column('processing_status', sa.String(), nullable=False, server_default='pending'))
    op.add_column('video', sa.Column('processing_error', sa.String(), nullable=True))
    op.add_column('video', sa.Column('available_qualities', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'available_qualities')
    op.drop_column('video', 'processing_error')
    op.drop_column('video', 'processing_status')
    op.drop_column('video', 'processed_video_url')
    op.drop_column('video', 'raw_video_key')
    op.drop_column('video', 'raw_video_url')
    # ### end Alembic commands ###
